### ISSUE TITLE
Crops not affected by hearth / boiler / icebox

### ISSUE THREAD

**Issue by luckygun** [KermitEmperor/CSL-Crops#2]
When farming crops in a closed room with a hearth in it the new temperature in the room won't affect the crops.

For example it is 35°C outside the room, the hearth is on cooling the room temperature to 26°C but the crops temperature shown with jade are at 36°C like it were outside.

![Image](https://github.com/user-attachments/assets/53e109f2-8ebb-49ee-9ba9-9fec04a8369e)
![Image](https://github.com/user-attachments/assets/26f4ac8d-c989-499c-ab84-57d53c216896)

I guess the crops are set on world temperature and not on the local temperature of the block they are in.

**Comment by luckygun** [comment]
I'am using a custom modpack not online yet on curseforge

mods lists : https://limewire.com/d/lb269#7UApbQtekj
the world i am using : https://limewire.com/d/wLAiI#YWqpKT2sV1

**Comment by KermitEmperor** [comment]
may i aswell get the datapack that is used to set the values for the plants? however I've seen that the version you are using isn't the latest, so i recommend updating as it may have been fixed

**Comment by luckygun** [comment]
added by this mod : https://www.curseforge.com/minecraft/mc-mods/cold-sweat-addon-hardcore-crops

**Comment by luckygun** [comment]
I just tryed with vanilla crops (carrot), the problem stay, the crop doesn't consider the room temp

**Comment by KermitEmperor** [comment]
I have concluded that Heart does not actually decrease the temperature, it just gives a special effect to the player, however what does work is boiler and icebox

**Comment by luckygun** [comment]
The ice box block itself make some cold on the block just around it, but when placing a smokestack the problem persist.
outside temp: 31°
inside temp with hearth : 31 - 6 ° 
inside temp with icebox : 31 - 3 °
the crops not directly next to the hearth or icebox still register at 31° and die over time

![Image](https://github.com/user-attachments/assets/cfae16fa-8420-4836-9920-64055cc7ed8b)
![Image](https://github.com/user-attachments/assets/8d843843-c7ca-4e58-9af7-ec2703aecfa0)
![Image](https://github.com/user-attachments/assets/73d5e0e1-7c23-4bce-a9b2-71541209434f)
